export const SET_POSITION = 'SET_POSITION';
export const SET_SEARCHED_POSITIONS = 'SET_SEARCHED_POSITIONS';
export const SET_POSITIONS = 'SET_POSITIONS';
export const ADD_NEW_POSITION = 'ADD_NEW_POSITION';
export const SET_POSITION_DETAIL = 'SET_POSITION_DETAIL';
export const SET_POSITION_VALUE = 'SET_POSITION_VALUE';
export const SET_POSITION_DEFAULT = 'SET_POSITION_DEFAULT';