export const SET_PROFILE_DATA = 'SET_PROFILE_DATA';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_PROFILE_FILE = 'SET_PROFILE_FILE';
export const UPDATE_FILES = 'UPDATE_FILES';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';


// FOR DASHBOARD
export const SET_STUDENTS_DASH = 'SET_STUDENTS_DASH';
export const SET_PERSONNEL_DASH = 'SET_PERSONNEL_DASH';
export const SET_OFFICES_DASH = 'SET_OFFICES_DASH';
export const SET_DOCUMENTS_DASH = 'SET_DOCUMENTS_DASH';