export const SET_PROFILE_DATA_STU = 'SET_PROFILE_DATA_STU';
export const SET_USER_INFO_STU = 'SET_USER_INFO_STU';
export const SET_PROFILE_FILE_STU = 'SET_PROFILE_FILE_STU';
export const UPDATE_FILES_STU = 'UPDATE_FILES_STU';
export const SET_USER_AVATAR_STU = 'SET_USER_AVATAR_STU';