export const SET_STUDENT = 'SET_STUDENT';
export const SET_SEARCHED_STUDENTS = 'SET_SEARCHED_STUDENTS';
export const SET_STUDENTS = 'SET_STUDENTS';
export const ADD_NEW_STUDENT = 'ADD_NEW_STUDENT';
export const SET_STUDENT_DETAIL = 'SET_STUDENT_DETAIL';
export const SET_STUDENT_VALUE = 'SET_STUDENT_VALUE';
export const SET_STUDENT_AVATAR = 'SET_STUDENT_AVATAR';
export const SET_STUDENT_DEFAULT = 'SET_STUDENT_DEFAULT';
export const SET_STUDENTS_DOCUMENTS = 'SET_STUDENTS_DOCUMENTS';

