export const SET_DOCUMENT = 'SET_DOCUMENT';
export const SET_SEARCHED_DOCUMENTS = 'SET_SEARCHED_DOCUMENTS';
export const SET_DOCUMENTS = 'SET_DOCUMENTS';
export const ADD_NEW_DOCUMENT = 'ADD_NEW_DOCUMENT';
export const SET_DOCUMENT_DETAIL = 'SET_DOCUMENT_DETAIL';
export const SET_DOCUMENT_VALUE = 'SET_DOCUMENT_VALUE';
export const SET_DOCUMENT_DEFAULT = 'SET_DOCUMENT_DEFAULT';
export const SET_DOCUMENTS_OFFICES = 'SET_DOCUMENTS_OFFICES';

export const SET_DOCUMENTS_INCOMING = 'SET_DOCUMENTS_INCOMING';
export const SET_DOCUMENTS_INCOMING_SEARCHED = 'SET_DOCUMENTS_INCOMING_SEARCHED';

export const SET_DOCUMENTS_RECEIVED = 'SET_DOCUMENTS_RECEIVED';
export const SET_DOCUMENTS_RECEIVED_SEARCHED = 'SET_DOCUMENTS_RECEIVED_SEARCHED';

export const SET_DOCUMENTS_SEARCHED_STUD = 'SET_DOCUMENTS_SEARCHED_STUD';

export const SET_DOCUMENT_TEMP_STUDENT = 'SET_DOCUMENT_TEMP_STUDENT';

